# $pfx_cert = Get-Content '.\OutlookOldDefaultThemeAddIn_TemporaryKey.pfx' -Encoding Byte
# [System.Convert]::ToBase64String($pfx_cert) | Write-Host

name: Build and Publish Add-In

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      
    - name: Decode the pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.signingcert }}")
        $certificatePath = Join-Path -Path ${{github.workspace}}\OutlookOldDefaultThemeAddIn -ChildPath OutlookOldDefaultThemeAddIn_TemporaryKey.pfx
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
        Import-PfxCertificate -FilePath ${{github.workspace}}\OutlookOldDefaultThemeAddIn\OutlookOldDefaultThemeAddIn_TemporaryKey.pfx -CertStoreLocation Cert:\CurrentUser\My
  
    - name: Build VSTO
      run: msbuild ${{github.workspace}}\OutlookOldDefaultThemeAddIn.sln /target:"clean;publish" /p:Platform="Any CPU" /p:Configuration="Release" /p:VisualStudioVersion="17.0"

    - name: Remove the pfx
      run: |
        Remove-Item -Path ${{github.workspace}}\OutlookOldDefaultThemeAddIn\OutlookOldDefaultThemeAddIn_TemporaryKey.pfx
        Get-ChildItem -Path Cert:\CurrentUser\My | ForEach-Object { Remove-Item $_.PSPath }

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: OneClickInstaller
        path: ${{github.workspace}}\OutlookOldDefaultThemeAddIn\bin\Release\app.publish